name: data_model
description: Base tools to create data models
version: 0.1.0
homepage: https://github.com/alexd1971/data_model
author: Aleksey Danilevskiy <alexey.danilevsky@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  quiver_hashcode: ^2.0.0

dev_dependencies:
  test: ^1.0.0
